In [1]:
import pandas as pd

In [4]:
df = pd.read_excel("C:/Users/karan/Downloads/Online Retail.xlsx")

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df['CustomerID'] = df['CustomerID'].fillna("Guest")
df['CustomerID'] = df['CustomerID'].astype(str)

In [9]:
df['CustomerID'].head()

0    17850.0
1    17850.0
2    17850.0
3    17850.0
4    17850.0
Name: CustomerID, dtype: object

In [10]:
df['Description'] = df['Description'].fillna("Unknown Product")

In [11]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [12]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    541909 non-null  object
 1   stockcode    541909 non-null  object
 2   description  541909 non-null  object
 3   quantity     541909 non-null  int64
 4   invoicedate  541909 non-null  datetime64[ns]
 5   unitprice    541909 non-null  float64
 6   customerid   541909 non-null  object
 7   country      541909 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 33.1+ MB

In [19]:
df = df.drop_duplicates()
df = df[(df['quantity'] > 0) & (df['unitprice'] > 0)]
df['invoicedate'] = pd.to_datetime(df['invoicedate'])

df['totalprice'] = df['quantity'] * df['unitprice']

In [20]:
df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,totalPrice,totalprice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,20.34

In [21]:
top_products = df.groupby('description')['quantity'].sum().sort_values(ascending=False).head(10)
print(top_products)

description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54951
JUMBO BAG RED RETROSPOT               48371
WHITE HANGING HEART T-LIGHT HOLDER    37872
POPCORN HOLDER                        36749
PACK OF 72 RETROSPOT CAKE CASES       36396
ASSORTED COLOUR BIRD ORNAMENT         36362
RABBIT NIGHT LIGHT                    30739
MINI PAINT SET VINTAGE                26633
Name: quantity, dtype: int64

In [22]:
country_sales = df.groupby('country')['totalprice'].sum().sort_values(ascending=False)
print(country_sales.head(10))

country
United Kingdom    9001744.094
Netherlands        285446.340
EIRE               283140.520
Germany            228678.400
France             209625.370
Australia          138453.810
Spain               61558.560
Switzerland         57067.600
Belgium             41196.340
Sweden              38367.830
Name: totalprice, dtype: float64

In [24]:
# RFM 
snapshot_date = df['invoicedate'].max() + pd.Timedelta(days=1)

In [25]:
rfm = df.groupby('customerid').agg({
    'invoicedate': lambda x: (snapshot_date - x.max()).days,
    'invoiceno': 'nunique',
    'totalprice': 'sum'
})

In [26]:
rfm.columns = ['recency', 'frequency', 'monetary']
rfm = rfm.reset_index()

In [28]:
rfm.head()

  customerid  recency  frequency  monetary
0    12346.0      326          1  77183.60
1    12347.0        2          7   4310.00
2    12348.0       75          4   1797.24
3    12349.0       19          1   1757.55
4    12350.0      310          1    334.40

In [29]:
rfm['r_score'] = pd.qcut(rfm['recency'], 4, labels=[4,3,2,1])
rfm['f_score'] = pd.qcut(rfm['frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['m_score'] = pd.qcut(rfm['monetary'], 4, labels=[1,2,3,4])

In [31]:
rfm['rfm_score'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str) + rfm['m_score'].astype(str)

In [32]:
rfm.head()

  customerid  recency  frequency  monetary r_score f_score m_score rfm_score
0    12346.0      326          1  77183.60       1       1       4       114
1    12347.0        2          7   4310.00       4       4       4       444
2    12348.0       75          4   1797.24       2       3       4       234
3    12349.0       19          1   1757.55       3       1       4       314
4    12350.0      310          1    334.40       1       1       2       112

In [42]:
print(df.columns)

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country', 'totalPrice', 'totalprice'],
      dtype='object')

In [47]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [48]:
df = df.loc[:, ~df.columns.duplicated()]

In [49]:
print(df.columns)

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country', 'totalprice'],
      dtype='object')

In [50]:
from sqlalchemy import create_engine

In [51]:
username = "root"
password = "Kaikira820"
host = "localhost"
port = "3306"
database = "online_retail" 

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = 'retail_data'
df.to_sql(table_name,engine,if_exists="replace",index = False)

524878